export enum NINJA_LEVEL {
  NOOBIE = 'NOOBIE',
  GENIN = 'GENIN',
  CHUNIN = 'CHUNIN',
  JONIN = 'JONIN',
  KAGE = 'KAGE',
}

export enum NINJA_WEAPON {
  SHURIKEN = 'SHURIKEN',
  KUNAI = 'KUNAI',
  SWORD = 'SWORD',
  WIND_SHURIKEN = 'WIND_SHURIKEN',
  NEEDLE = 'NEEDLE',
  SPIKE = 'SPIKE',
  BOMB = 'BOMB',
  SPECIAL = 'SPECIAL',
}

export enum ATTACK_RANGE {
  CLOSE_RANGE = 'GENIN',
  LONG_RANGE = 'CHUNIN',
  LONG_AND_CLOSE_RANGE = 'LONG_AND_CLOSE_RANGE',
}
